version: '3.3'

services:
  app:
    image: skypro_test
  pd:
    image: postgres
    entrypoint:
      - POSTGRES_USER=${{DB_NAME}}
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=flask_app
    ports:
      - "5432:5432"