version: '3.3'

services:
  api:
    build:
      context: .
    ports:
      - 80:80
  pg:
    image: postgres
    entrypoint:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=flask_app
    ports:
      - "5432:5432"